name: agify
description: A case-study project for Bling.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^2.4.0
  dio: ^5.2.1+1
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_launcher_icons: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner:
  freezed: ^2.3.5
  json_serializable: ^6.7.1
  flutter_native_splash: ^2.2.7

flutter_icons:    
 android: "launcher_icon"    
 ios: true    
 image_path: "assets/app_icons/app_icon.png"
 adaptive_icon_foreground: "assets/app_icons/app_icon.png"
 adaptive_icon_background: "#ECE0C2"
 adaptive_icon_padding: true

flutter_native_splash:
  color: "#ECE0C2"
  image: assets/app_icons/splash.png
  android: true
  ios: true
  web: true


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/

  fonts:
    - family: Recoleta
      fonts:
        - asset: assets/fonts/recoleta/Recoleta-Bold.ttf
        - asset: assets/fonts/recoleta/Recoleta-Medium.ttf
        - asset: assets/fonts/recoleta/Recoleta-Regular.ttf
        - asset: assets/fonts/recoleta/Recoleta-SemiBold.ttf



    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
